import guiCodeSwitcher  from "../utils/guiCodeSwitcher.js"
import showHideMenu     from "../utils/editMenu.js"
import fixSelected      from "../utils/fixSelected.js"
import doTheFetch       from "./editArticle.js"
import characterCounter from "../utils/characterCounter.js"
import sanitizeInput    from "../utils/makePageNavUneditable.js"